# 使用 CentOS 7 作为基础镜像 (已包含 GCC 11)
FROM registry.cn-hangzhou.aliyuncs.com/zarra/devtoolset:11

# --- 1. 激活 devtoolset-11 (环境变量持久化) ---
ENV PATH=/opt/rh/devtoolset-11/root/usr/bin:$PATH \
    LD_LIBRARY_PATH=/opt/rh/devtoolset-11/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib:$LD_LIBRARY_PATH \
    PKG_CONFIG_PATH=/opt/rh/devtoolset-11/root/usr/lib64/pkgconfig:$PKG_CONFIG_PATH \
    MANPATH=/opt/rh/devtoolset-11/root/usr/share/man:$MANPATH


# ---  安装 Rust ---
# 将 Rust 相关环境全部放在 /opt/rust 下
ENV RUSTUP_HOME=/opt/rust/rustup \
    CARGO_HOME=/opt/rust/cargo \
    RUSTUP_DIST_SERVER=https://rsproxy.cn \
    RUSTUP_UPDATE_ROOT=https://rsproxy.cn/rustup

# 提前把路径加进去，这样就不需要 source 任何文件了
ENV PATH=$CARGO_HOME/bin:$PATH

COPY rustup-init.sh /tmp/rustup-init.sh

RUN mkdir -p /opt/rust && \
    chmod +x /tmp/rustup-init.sh && \
    # 使用 --default-toolchain stable 确保安装稳定版
    /tmp/rustup-init.sh -y --no-modify-path --default-toolchain stable && \
    rm /tmp/rustup-init.sh
    # 这一行如果文件太多会很慢，如果不需要非 root 用户写，可以删掉或者只改顶层权限
RUN chmod -R 755 /opt/rust

# --- 3. 安装 Golang (紧接着 Rust) ---
ENV GO_VERSION=1.20.14 \
    GOROOT=/opt/golang \
    GOPATH=/go \
    GOPROXY=https://goproxy.cn,direct
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH

RUN mkdir -p $GOROOT && \
    wget https://golang.google.cn/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C $GOROOT --strip-components=1 -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
    rm go${GO_VERSION}.linux-amd64.tar.gz && \
    mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"


# --- 验证安装 ---
RUN gcc --version && go version && rustc --version

WORKDIR /workspace
CMD ["/bin/bash"]